<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__f_entryid12</name>
   <tag></tag>
   <elementGuidId>a7d461d1-5431-42d0-a39f-3fdeb0abd34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='f_entryid12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;f_entryid12&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>260bd04f-ea72-43c5-b4ac-d46029316dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>84fbfac8-df23-44e8-9944-a63b8094e94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f_entryid12</value>
      <webElementGuid>a3de8d42-e694-44a8-b81e-6fa363aea586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>4aa657c1-91b9-4eff-809c-acf6e87d2d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/table[3]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[8]/td[@class=&quot;normalDetail&quot;]/input[1]</value>
      <webElementGuid>1921f0a1-ca9a-4f33-af09-641ac9f5b815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='f_entryid12']</value>
      <webElementGuid>97791d28-8d29-4b89-ad30-f6ad5b499dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/table[3]/tbody/tr/td[2]/table/tbody/tr[8]/td[5]/input</value>
      <webElementGuid>667218cb-b918-456c-a2c5-a50e9931c6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[5]/input</value>
      <webElementGuid>eebf661d-0708-4f69-afd6-b91db6c4253f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'f_entryid12']</value>
      <webElementGuid>4eb4c6a9-7ce3-48c2-a131-d04b6d7ddf3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
