<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__f_entryid10</name>
   <tag></tag>
   <elementGuidId>820e0afb-beab-42c8-bd94-bdf85bf1263a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='f_entryid10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;f_entryid10&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b897741b-76d6-4d61-b971-507d03b775f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>912181bb-9cd0-4ee1-a73d-65c802ce2273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f_entryid10</value>
      <webElementGuid>313651e6-8ba2-4df5-97b3-cc49a40e68c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>ebb8598c-40c3-4195-87b8-a3f3ff86ff1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>isThaichar(this.value,this)</value>
      <webElementGuid>b24ed486-3838-4c36-9769-e133318091f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/table[3]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[7]/td[@class=&quot;normalDetail&quot;]/input[1]</value>
      <webElementGuid>f9182b70-851f-4975-bd89-af3fa50d9e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='f_entryid10']</value>
      <webElementGuid>6196455d-917e-4585-9124-363ba9717f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/table[3]/tbody/tr/td[2]/table/tbody/tr[7]/td[5]/input</value>
      <webElementGuid>15a405d0-0b4c-4d10-9c2e-04dc58d41fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>c0f925f3-9691-4988-8ad2-4cdd9576dda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'f_entryid10']</value>
      <webElementGuid>53997cbb-4ff0-4573-a04f-ca27d1c5addf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
