<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>2bd61455-433e-41c0-a748-37312219e614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Regis&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b9259ab-e24f-4f44-9ca0-dc71fe819374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://reg.npru.ac.th/registrar/appbioentryconfigregis.asp?avs1034829644=1</value>
      <webElementGuid>9f68d430-a2b5-43b8-b944-160676cacbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Regis</value>
      <webElementGuid>c605c7b9-3951-4587-b4f8-a407e95b872d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ลงทะเบียนเข้าใช้ระบบ</value>
      <webElementGuid>d1334e09-8ec4-4762-953e-84577caed047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>d3369274-83c2-4f61-a0a4-0b847520febd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li/a</value>
      <webElementGuid>202f30ca-5515-425a-9ed3-e95f01d5ad18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ลงทะเบียนเข้าใช้ระบบ')]</value>
      <webElementGuid>4103165f-58b7-465f-8605-ffa113986f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เมนูหลัก'])[1]/following::a[1]</value>
      <webElementGuid>b534cfaf-69c9-44a7-985c-be603a7eb285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เข้าสู่ระบบ'])[1]/preceding::a[1]</value>
      <webElementGuid>d3dc9fd0-08bc-42af-816a-ee811a03b154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สาขาและจำนวนที่รับสมัคร'])[1]/preceding::a[2]</value>
      <webElementGuid>61b7a31d-a654-4f79-b049-6a256f81a113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลงทะเบียนเข้าใช้ระบบ']/parent::*</value>
      <webElementGuid>b221e1be-6e14-4130-b73f-42ee1167d9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://reg.npru.ac.th/registrar/appbioentryconfigregis.asp?avs1034829644=1')]</value>
      <webElementGuid>374d439e-3c49-43b5-a1a1-a7db9637a55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>96b683a9-29f6-4ba3-a8cc-ac334c818c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://reg.npru.ac.th/registrar/appbioentryconfigregis.asp?avs1034829644=1' and @title = 'Regis' and (text() = 'ลงทะเบียนเข้าใช้ระบบ' or . = 'ลงทะเบียนเข้าใช้ระบบ')]</value>
      <webElementGuid>161e7871-d066-4aa8-a8c7-447a6bdcfb13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
