<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>25458e79-7fe0-4a53-b98a-129d79ab77b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Regis&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d892113d-fe1c-475b-bcc9-0244814d2dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://reg.npru.ac.th/registrar/appbioentryconfigregis.asp?avs1034829662=1</value>
      <webElementGuid>a74f0424-7844-4a52-a050-40ba75b37629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Regis</value>
      <webElementGuid>99bef331-6c22-4465-82cb-c1b89a4be4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ลงทะเบียนเข้าใช้ระบบ</value>
      <webElementGuid>3ff49e24-8be0-44a5-a5b5-19894404ac4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>7ff452b7-c9fd-402e-9108-8ff5539e2a8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li/a</value>
      <webElementGuid>b4139bb9-9e6b-450e-836e-a2ab0b853ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ลงทะเบียนเข้าใช้ระบบ')]</value>
      <webElementGuid>a2b900bc-2ee5-4480-b518-432f1b402f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เมนูหลัก'])[1]/following::a[1]</value>
      <webElementGuid>095158c8-9dbd-425e-9ba6-d8947208169f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เข้าสู่ระบบ'])[1]/preceding::a[1]</value>
      <webElementGuid>b56d4e77-beed-4195-a2f5-3f90c1da40f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สาขาและจำนวนที่รับสมัคร'])[1]/preceding::a[2]</value>
      <webElementGuid>b047045c-7754-4e0c-9948-583815a58808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลงทะเบียนเข้าใช้ระบบ']/parent::*</value>
      <webElementGuid>d4aa4f28-9b7b-4ac6-a6a1-876231b9b3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://reg.npru.ac.th/registrar/appbioentryconfigregis.asp?avs1034829662=1')]</value>
      <webElementGuid>7c90c20e-bf6d-433f-8703-1a56d2796db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>7198e63b-3adb-4b64-975d-648d5c218408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://reg.npru.ac.th/registrar/appbioentryconfigregis.asp?avs1034829662=1' and @title = 'Regis' and (text() = 'ลงทะเบียนเข้าใช้ระบบ' or . = 'ลงทะเบียนเข้าใช้ระบบ')]</value>
      <webElementGuid>4f6a7c97-0e96-45f8-b7aa-f32737ff51fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
