<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>5e4014a5-04f4-4f16-bd67-6031636713f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Home&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dbff940-ba61-45f4-8851-f952db3ecb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://reg.npru.ac.th/registrar/apphome.asp</value>
      <webElementGuid>6e6ad119-edd0-4dca-9f04-b8024e9dc1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>53f82210-c21c-4c70-acb9-9b407fa96efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ถอยกลับ</value>
      <webElementGuid>90c1afb7-e8b1-4c34-9799-1b1dc3c456c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>51ab157d-f14e-409f-a6ba-1e6a91f8383e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li/a</value>
      <webElementGuid>caffeda7-0e98-40f6-9e99-5eb1e24592fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ถอยกลับ')]</value>
      <webElementGuid>720bdcb7-1fa1-42b3-b1e4-af0f3f58bdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เมนูหลัก'])[1]/following::a[1]</value>
      <webElementGuid>0a9acef3-3ed9-4f93-8d96-22c4366dc2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ลงทะเบียนผู้สมัคร'])[1]/preceding::a[1]</value>
      <webElementGuid>5382779f-3611-408b-8eb3-883f85089666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ถอยกลับ']/parent::*</value>
      <webElementGuid>dee8d3c0-024d-45a1-b39a-e01ff10713ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://reg.npru.ac.th/registrar/apphome.asp']</value>
      <webElementGuid>b020bf6c-1669-4a38-a296-44e5421683fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>0f5bb3af-093b-4c77-97a7-d031f3759f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://reg.npru.ac.th/registrar/apphome.asp' and @title = 'Home' and (text() = 'ถอยกลับ' or . = 'ถอยกลับ')]</value>
      <webElementGuid>6454434a-3b53-4e09-b246-3c006739daca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
