<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__f_entryid6</name>
   <tag></tag>
   <elementGuidId>3d7bb53e-f495-47f5-9305-ee48518c0033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='f_entryid6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;f_entryid6&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc41fb48-2e32-4261-8fe3-368ce67f8a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>c82ebf48-c241-44e2-85b9-a16f819c041d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f_entryid6</value>
      <webElementGuid>22d7da36-7d64-4643-aa6e-e96d81435b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>76e1850c-f874-44e3-8eaf-e5ece6cf34c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/table[3]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[5]/td[@class=&quot;normalDetail&quot;]/input[1]</value>
      <webElementGuid>7c438cc4-591c-4265-ba81-8f883e189b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='f_entryid6']</value>
      <webElementGuid>fef77ff5-3ad2-4843-b0aa-e88c2f6bca2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/table[3]/tbody/tr/td[2]/table/tbody/tr[5]/td[3]/input</value>
      <webElementGuid>55869af8-ef0d-49c9-8054-4f2a1b729bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>1be8da25-74d5-42cd-ab99-ab9d2b23335b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'f_entryid6']</value>
      <webElementGuid>86adc794-035b-4a99-84d6-80494e35c8c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
