<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_( 13   )</name>
   <tag></tag>
   <elementGuidId>7f137816-8e55-48b9-8eeb-84933146e09f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/table[3]/tbody/tr/td[2]/table/tbody/tr[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>523490eb-1154-40f1-a6be-0450c2de2f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>TOP</value>
      <webElementGuid>4e5cf7ff-1878-4433-a55f-3642bd581d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   เลขประจำตัวประชาชน/หนังสือเดินทาง  (เฉพาะตัวเลข 13 หลักไม่ต้องเว้นวรรค หรือ ขีดคั่น) * </value>
      <webElementGuid>5f868af4-0fc1-4f87-a275-76b9d10891b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/table[3]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[5]</value>
      <webElementGuid>0c2ffde1-51d9-4891-84e2-886efd8a0a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/table[3]/tbody/tr/td[2]/table/tbody/tr[5]</value>
      <webElementGuid>c821b878-ad2c-440e-af85-2516f9a5fd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::tr[1]</value>
      <webElementGuid>ecd3cb9c-d054-4172-bf60-aa3ab49c70c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]</value>
      <webElementGuid>12178d5b-8d19-443e-8e40-8c9b1081d481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[(text() = '   เลขประจำตัวประชาชน/หนังสือเดินทาง  (เฉพาะตัวเลข 13 หลักไม่ต้องเว้นวรรค หรือ ขีดคั่น) * ' or . = '   เลขประจำตัวประชาชน/หนังสือเดินทาง  (เฉพาะตัวเลข 13 หลักไม่ต้องเว้นวรรค หรือ ขีดคั่น) * ')]</value>
      <webElementGuid>4151c1c1-aff6-4b48-9fbf-a3a82b78b46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
